# Generated by Django 2.0 on 2018-01-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=20)),
                ('admin_pwd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('coin_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(max_length=64)),
                ('is_spent', models.BooleanField(default=False)),
                ('timestamp', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('data_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('data_name', models.CharField(max_length=64)),
                ('data_info', models.CharField(max_length=200)),
                ('timestamp', models.CharField(max_length=32)),
                ('data_source', models.CharField(max_length=20)),
                ('data_type', models.CharField(max_length=20)),
                ('data_tag', models.CharField(max_length=100)),
                ('data_address', models.CharField(max_length=200)),
                ('data_status', models.CharField(max_length=20)),
                ('data_md5', models.CharField(max_length=64)),
                ('data_size', models.FloatField()),
                ('data_download', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('data_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('notice_info', models.CharField(max_length=200)),
                ('if_check', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('recharge_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('timestamp', models.CharField(max_length=32)),
                ('credits', models.FloatField()),
                ('before_account', models.FloatField()),
                ('after_account', models.FloatField()),
                ('coin_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewer_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('data_id', models.CharField(max_length=64)),
                ('review_status', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Transcation',
            fields=[
                ('transaction_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('buyer_id', models.CharField(max_length=64)),
                ('seller_id', models.CharField(max_length=64)),
                ('data_id', models.CharField(max_length=64)),
                ('timestamp', models.CharField(max_length=32)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('user_pwd', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_realName', models.CharField(default='', max_length=20)),
                ('user_phone', models.CharField(default=0, max_length=20)),
                ('user_idcard', models.CharField(default=0, max_length=20)),
                ('user_company', models.CharField(default='', max_length=64)),
                ('user_title', models.CharField(default=0, max_length=20)),
                ('user_addr', models.CharField(default='China', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('account', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='download',
            unique_together={('user_id', 'data_id')},
        ),
    ]
