# Generated by Django 2.0 on 2018-03-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSCapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('timestamp', models.CharField(max_length=32)),
                ('block_size', models.FloatField()),
                ('tx_number', models.IntegerField()),
            ],
        ),
    ]
