# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSCapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='data_purchase',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
