# Generated by Django 2.0 on 2018-07-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSCapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('tx_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('timestamp', models.CharField(max_length=64)),
                ('science_data_id_list', models.CharField(default='', max_length=2000)),
                ('conference_data_id_list', models.CharField(default='', max_length=2000)),
                ('journal_data_id_list', models.CharField(default='', max_length=2000)),
                ('patent_data_id_list', models.CharField(default='', max_length=2000)),
                ('action', models.CharField(max_length=64)),
                ('first_title', models.CharField(default='', max_length=64)),
                ('second_title', models.CharField(default='', max_length=64)),
                ('block_height', models.IntegerField(default=0)),
                ('reviewer', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
