# Generated by Django 2.0 on 2018-03-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSCapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reset',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('secretKey', models.CharField(max_length=64, unique=True)),
                ('last_reset_time', models.CharField(max_length=32)),
            ],
        ),
    ]
