# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSCapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_status',
            field=models.IntegerField(),
        ),
    ]
