# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BSCapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Download',
            new_name='Purchase',
        ),
    ]
