# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSCapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_addr',
            field=models.CharField(default='China', max_length=64),
        ),
    ]
