# Generated by Django 2.0 on 2018-07-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSCapp', '0002_operationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='block_timestamp',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='nonce',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='prev_hash',
            field=models.CharField(default='', max_length=64),
        ),
    ]
