# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSCapp', '0002_auto_20180122_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_md5',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='data_size',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
