# Generated by Django 2.0 on 2018-07-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSCapp', '0002_remove_sciencedata_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('data_id', models.CharField(max_length=64)),
                ('timestamp', models.CharField(max_length=64)),
                ('action', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='downloadlog',
            unique_together={('user_id', 'timestamp', 'data_id')},
        ),
    ]
