# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSCapp', '0002_auto_20180125_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_download',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_purchase',
            field=models.IntegerField(default=0),
        ),
    ]
