# Generated by Django 2.0 on 2018-03-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSCapp', '0002_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='if_delete',
            field=models.BooleanField(default=False),
        ),
    ]
