# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSCapp', '0003_auto_20180123_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_download',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
