# Generated by Django 2.0 on 2018-07-09 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BSCapp', '0004_auto_20180709_0326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckLog',
        ),
    ]
