# Generated by Django 2.0 on 2018-05-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSCapp', '0004_modify'),
    ]

    operations = [
        migrations.CreateModel(
            name='TxLog',
            fields=[
                ('TxLog_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('timestamp', models.CharField(max_length=32)),
                ('credits', models.FloatField()),
                ('before_account', models.FloatField()),
                ('after_account', models.FloatField()),
                ('action', models.IntegerField(default=0)),
                ('data_id', models.CharField(max_length=64)),
            ],
        ),
    ]
