# Generated by Django 2.0 on 2018-07-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSCapp', '0005_txlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('article_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('article_name', models.CharField(default='', max_length=400)),
                ('article_authors', models.CharField(default='', max_length=400)),
                ('conference_name', models.CharField(default='', max_length=400)),
                ('keywords', models.CharField(default='', max_length=400)),
                ('abstract', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('article_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('article_name', models.CharField(default='', max_length=400)),
                ('article_authors', models.CharField(default='', max_length=400)),
                ('journal_name', models.CharField(default='', max_length=200)),
                ('keywords', models.CharField(default='', max_length=400)),
                ('abstract', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('patent_openId', models.CharField(max_length=64)),
                ('patent_name', models.CharField(max_length=100)),
                ('patent_applicant', models.CharField(max_length=100)),
                ('patent_authors', models.CharField(max_length=200)),
                ('patent_keywords', models.CharField(max_length=400)),
                ('patent_province', models.CharField(max_length=20)),
            ],
        ),
    ]
