# Generated by Django 2.0 on 2018-07-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSCapp', '0006_newblock_block_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newblock',
            name='nonce',
            field=models.CharField(default='', max_length=64),
        ),
    ]
