# Generated by Django 2.0 on 2018-07-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSCapp', '0007_auto_20180709_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='data_type',
            field=models.CharField(default='', max_length=64),
        ),
    ]
