# Generated by Django 2.0 on 2018-07-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BSCapp', '0008_operationlog_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newblock',
            name='block_height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='newblock',
            name='tx_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
